### ISSUE TITLE
thread/movedown

### ISSUE THREAD

**Issue by AeronautYuFan** [AeronautYuFan/tetris#1]
when you hold down the down arrow key, it messes with threading and makes it go below the screen

possible solution: make another collisionFloor checker for the movedown method, and if it is too close to the floor then down arrow does nothing

`Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 21
	at gameBoard.collisionFloor(gameBoard.java:93)
	at gameBoard$1.run(gameBoard.java:36)`

`Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 21
	at gameBoard.collisionFloor(gameBoard.java:93)
	at gameBoard$1.run(gameBoard.java:36)`

`Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: Index 39 out of bounds for length 21
	at gameBoard.collisionFloor(gameBoard.java:93)
	at gameBoard$1.run(gameBoard.java:36)`

**Comment by AeronautYuFan** [comment]
fixed (removed threadding)
